version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    networks:
      - backend-network
  
  backend:
    image: node:20-alpine
    volumes:
      - ./backend:/app
    working_dir: /app
    command: npm run start:docker
    depends_on:
      - postgres
    ports:
      - 3000:3000
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge